# histogram_config.yaml
save_base: 3_param_trained_models
out_dir: "{save_base}/{num_samples}totalsamples_histogram_{n_bins}bins_nsf_h{hidden_features}_t{num_transforms}"

wandb:
  project: "my-sbi-project"
  entity: "plt109"
  group: "ambe-3param"

data:
  base_dir: /home/puehlengt/appletree/notebooks
  fname: harvested_testsims_3params.npy
  num_samples: 50000

histogram:
  n_bins: 25
  cs1_range: [0, 150]
  log_cs2_range: [2.1, 4.1]

model:
  type: nsf
  hidden_features: 128
  num_transforms: 5

training:
  batch_size: 32
  learning_rate: 0.0001
  stop_after_epochs: 20
